In [1]:
import pandas as pd
import numpy as np


In [269]:
train=pd.read_csv("data_train.csv",delimiter=",")

In [270]:
train_data=train

In [271]:
train_data.shape

(596000, 58)

In [273]:
train_data.describe()

id           num1           num2           num3  \
count  596000.000000  596000.000000  596000.000000  596000.000000   
mean   297999.500000       1.900423       4.423356       0.393743   
std    172050.524555       1.983855       2.699861       0.488579   
min         0.000000       0.000000       0.000000       0.000000   
25%    148999.750000       0.000000       2.000000       0.000000   
50%    297999.500000       1.000000       4.000000       0.000000   
75%    446999.250000       3.000000       6.000000       1.000000   
max    595999.000000       7.000000      11.000000       1.000000   

                num4           num5           num6           num7  \
count  596000.000000  596000.000000  596000.000000  596000.000000   
mean        0.257015       0.163933       0.185309       0.000374   
std         0.436988       0.370215       0.388548       0.019340   
min         0.000000       0.000000       0.000000       0.000000   
25%         0.000000       0.000000       0.000000       0.000000   
50%         0.000000       0.000000       0.000000       0.000000   
75%         1.000000       0.000000       0.000000       0.000000   
max         1.000000       1.000000       1.000000       1.000000   

                num8           num9      ...                 cat6  \
count  596000.000000  596000.000000      ...        184208.000000   
mean        0.001693       0.009435      ...             0.601744   
std         0.041111       0.096672      ...             0.489540   
min         0.000000       0.000000      ...             0.000000   
25%         0.000000       0.000000      ...             0.000000   
50%         0.000000       0.000000      ...             1.000000   
75%         0.000000       0.000000      ...             1.000000   
max         1.000000       1.000000      ...             1.000000   

                cat7           cat8           cat9          cat10  \
count  596000.000000  329072.000000  596000.000000  584497.000000   
mean        0.725106       0.525365       6.555000       0.947608   
std         2.153319       0.499357       5.501419       0.222817   
min         0.000000       0.000000       0.000000       0.000000   
25%         0.000000       0.000000       1.000000       1.000000   
50%         0.000000       1.000000       7.000000       1.000000   
75%         0.000000       1.000000      11.000000       1.000000   
max         9.000000       1.000000      17.000000       1.000000   

               cat11          cat12          cat13          cat14  \
count  596000.000000  595430.000000  596000.000000  596000.000000   
mean        0.832077       1.331161       0.992136      62.215570   
std         0.373798       0.976544       0.091613      33.012105   
min         0.000000       0.000000       0.000000       1.000000   
25%         1.000000       0.000000       1.000000      32.000000   
50%         1.000000       2.000000       1.000000      65.000000   
75%         1.000000       2.000000       1.000000      93.000000   
max         1.000000       4.000000       2.000000     104.000000   

              target  
count  596000.000000  
mean        0.036436  
std         0.187373  
min         0.000000  
25%         0.000000  
50%         0.000000  
75%         0.000000  
max         1.000000  

[8 rows x 58 columns]

# filling null entries of training data
all null entries is filled with the mean of corresponding feature

In [275]:
for i in range(58):
    current_mean=train_data.iloc[:,i].mean()
    train_data.iloc[:,i].fillna(current_mean,inplace=True)


In [276]:
train_data.isnull().sum()

id        0
num1      0
num2      0
num3      0
num4      0
num5      0
num6      0
num7      0
num8      0
num9      0
num10     0
num11     0
num12     0
num13     0
num14     0
num15     0
num16     0
num17     0
num18     0
num19     0
num20     0
num21     0
num22     0
num23     0
der1      0
der2      0
der3      0
der4      0
der5      0
der6      0
der7      0
der8      0
der9      0
der10     0
der11     0
der12     0
der13     0
der14     0
der15     0
der16     0
der17     0
der18     0
der19     0
cat1      0
cat2      0
cat3      0
cat4      0
cat5      0
cat6      0
cat7      0
cat8      0
cat9      0
cat10     0
cat11     0
cat12     0
cat13     0
cat14     0
target    0
dtype: int64

In [335]:
#--remove first row because most of the entries are null

train_data=train_data.iloc[1:,:]

In [278]:
train_data.shape

(595999, 58)

In [280]:
train_data.head()

id  num1  num2  num3  num4  num5  num6  num7  num8  num9   ...        cat6  \
1   1     1     7     0     0     1     0     0     0     0   ...    0.601744   
2   2     5     9     0     0     1     0     0     0     0   ...    0.601744   
3   3     0     2     1     0     0     0     0     0     0   ...    0.000000   
4   4     0     0     1     0     0     0     0     0     0   ...    0.601744   
5   5     5     4     0     0     0     1     0     0     0   ...    0.601744   

   cat7      cat8  cat9  cat10  cat11  cat12  cat13  cat14  target  
1     0  0.525365    11    1.0      1    2.0      1     19       0  
2     0  0.525365    14    1.0      1    2.0      1     60       0  
3     0  1.000000    11    1.0      1    3.0      1    104       0  
4     0  0.525365    14    1.0      1    2.0      1     82       0  
5     0  0.000000    14    1.0      1    0.0      1    104       0  

[5 rows x 58 columns]

# splitting the training data into X and Y

X contain the training features while Y contain target

In [281]:
X=train_data.iloc[:,:57]

In [282]:
Y=train_data.iloc[:,57]

In [283]:
Y

1         0
2         0
3         0
4         0
5         0
6         0
7         0
8         0
9         1
10        0
11        0
12        0
13        0
14        0
15        0
16        0
17        0
18        0
19        1
20        0
21        0
22        0
23        0
24        0
25        0
26        0
27        0
28        1
29        0
30        0
         ..
595970    0
595971    0
595972    0
595973    0
595974    0
595975    0
595976    0
595977    0
595978    0
595979    0
595980    0
595981    0
595982    0
595983    0
595984    0
595985    0
595986    0
595987    0
595988    0
595989    0
595990    0
595991    0
595992    0
595993    0
595994    0
595995    0
595996    0
595997    0
595998    0
595999    0
Name: target, Length: 595999, dtype: int64

In [284]:
X.head()

id  num1  num2  num3  num4  num5  num6  num7  num8  num9  ...    cat5  \
1   1     1     7     0     0     1     0     0     0     0  ...     1.0   
2   2     5     9     0     0     1     0     0     0     0  ...     1.0   
3   3     0     2     1     0     0     0     0     0     0  ...     1.0   
4   4     0     0     1     0     0     0     0     0     0  ...     1.0   
5   5     5     4     0     0     0     1     0     0     0  ...     0.0   

       cat6  cat7      cat8  cat9  cat10  cat11  cat12  cat13  cat14  
1  0.601744     0  0.525365    11    1.0      1    2.0      1     19  
2  0.601744     0  0.525365    14    1.0      1    2.0      1     60  
3  0.000000     0  1.000000    11    1.0      1    3.0      1    104  
4  0.601744     0  0.525365    14    1.0      1    2.0      1     82  
5  0.601744     0  0.000000    14    1.0      1    0.0      1    104  

[5 rows x 57 columns]

# applying pca on the training data

as the datset contain lots of correlated data in it. 
so to reduce the dimentionality of data i have applies pca on it.

kept variance is 0.99

In [285]:
from sklearn.decomposition import PCA 
pca=PCA()

In [286]:
X_transform=pca.fit_transform(X)

In [287]:
k=0
current_variance=0
total=sum(pca.explained_variance_)

while current_variance/total<=0.99:
  current_variance += pca.explained_variance_[k]
  k=k+1
k  

1

if i kept explained vaiance =0.99 than dimention can be reduced to 1, only 1 eigen vector is able to explaine 99% of the information
that reduced the dimensions a lot

In [288]:
pca=PCA(n_components=k,whiten=True)
X=pca.fit_transform(X)

In [289]:
X

array([[ 1.73204645],
       [ 1.73204064],
       [ 1.73203482],
       ...,
       [-1.73203482],
       [-1.73204064],
       [-1.73204645]])

In [290]:
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.model_selection import train_test_split

In [293]:
#-- splitting training data  further into training  and testing so that i can evaluate which algrithm will work better or for comaprision

x_train,x_test,y_train,y_test=train_test_split(X,Y)

In [294]:
x_test.shape

(149000, 1)

# importing random forest

In [301]:
from sklearn.ensemble import RandomForestClassifier

In [302]:
rf= RandomForestClassifier()

In [303]:
rf.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [304]:
rf_pred=rf.predict(x_test)

# checking for the precision and recall 

In [305]:
print(classification_report(y_test,rf_pred))

             precision    recall  f1-score   support

          0       0.96      0.97      0.97    143615
          1       0.03      0.03      0.03      5385

avg / total       0.93      0.94      0.93    149000



In [306]:
# analysing confusion matrix

confusion_matrix(rf_pred,y_test)

array([[139661,   5243],
       [  3954,    142]], dtype=int64)

In [337]:
(y_test==1).sum()

5385

In [307]:
(rf_pred==1).sum()

4096

# applying decision tree on the dummy training testing data that i have created

i tried two more classification algorithm like logistic regression they havent perform better than these two

In [309]:
from sklearn.tree import DecisionTreeClassifier

In [310]:
dt=DecisionTreeClassifier()

In [311]:
dt.fit(x_train,y_train)
dt_pred=dt.predict(x_test)

In [312]:
print(classification_report(y_test,dt_pred))

             precision    recall  f1-score   support

          0       0.96      0.96      0.96    143615
          1       0.03      0.03      0.03      5385

avg / total       0.93      0.93      0.93    149000



In [313]:
confusion_matrix(dt_pred,y_test)

array([[138337,   5201],
       [  5278,    184]], dtype=int64)

In [314]:
(y_test==1).sum()

5385

In [315]:
(dt_pred==1).sum()

5462

# both decision tree and random forest perform good on the dataset that i have created

# importing testing data

In [258]:
test_data=pd.read_csv("data_test.csv",delimiter=",")

In [262]:
# analysing the testing data

test_data.describe()

id           num1           num2           num3  \
count  8.928160e+05  892816.000000  892816.000000  892816.000000   
mean   7.441535e+05       1.902371       4.413734       0.393246   
std    4.296830e+05       1.986503       2.700149       0.488471   
min    0.000000e+00       0.000000       0.000000       0.000000   
25%    3.720218e+05       0.000000       2.000000       0.000000   
50%    7.443070e+05       1.000000       4.000000       0.000000   
75%    1.116308e+06       3.000000       6.000000       1.000000   
max    1.488026e+06       7.000000      11.000000       1.000000   

                num4           num5           num6           num7  \
count  892816.000000  892816.000000  892816.000000  892816.000000   
mean        0.257191       0.163659       0.185905       0.000373   
std         0.437086       0.369966       0.389030       0.019309   
min         0.000000       0.000000       0.000000       0.000000   
25%         0.000000       0.000000       0.000000       0.000000   
50%         0.000000       0.000000       0.000000       0.000000   
75%         1.000000       0.000000       0.000000       0.000000   
max         1.000000       1.000000       1.000000       1.000000   

                num8           num9      ...                 cat5  \
count  892816.000000  892816.000000      ...        892811.000000   
mean        0.001595       0.009376      ...             0.829951   
std         0.039905       0.096375      ...             0.375676   
min         0.000000       0.000000      ...             0.000000   
25%         0.000000       0.000000      ...             1.000000   
50%         0.000000       0.000000      ...             1.000000   
75%         0.000000       0.000000      ...             1.000000   
max         1.000000       1.000000      ...             1.000000   

                cat6           cat7           cat8           cat9  \
count  275905.000000  892816.000000  492457.000000  892816.000000   
mean        0.602138       0.725798       0.525717       6.564297   
std         0.489457       2.154886       0.499339       5.500485   
min         0.000000       0.000000       0.000000       0.000000   
25%         0.000000       0.000000       0.000000       1.000000   
50%         1.000000       0.000000       1.000000       7.000000   
75%         1.000000       0.000000       1.000000      11.000000   
max         1.000000       9.000000       1.000000      17.000000   

               cat10          cat11          cat12          cat13  \
count  875485.000000  892816.000000  891939.000000  892816.000000   
mean        0.947957       0.832311       1.330200       0.992134   
std         0.222114       0.373590       0.976495       0.091530   
min         0.000000       0.000000       0.000000       0.000000   
25%         1.000000       1.000000       0.000000       1.000000   
50%         1.000000       1.000000       2.000000       1.000000   
75%         1.000000       1.000000       2.000000       1.000000   
max         1.000000       1.000000       4.000000       2.000000   

               cat14  
count  892816.000000  
mean       62.284293  
std        33.003714  
min         1.000000  
25%        32.000000  
50%        65.000000  
75%        94.000000  
max       104.000000  

[8 rows x 57 columns]

In [263]:
test_data.isnull().sum()

id            0
num1          0
num2          0
num3          0
num4          0
num5          0
num6          0
num7          0
num8          0
num9          0
num10         0
num11         0
num12         0
num13         0
num14         0
num15         0
num16         0
num17         0
num18    161684
num19         1
num20         0
num21         0
num22     63805
num23         0
der1          0
der2          0
der3          0
der4          0
der5          0
der6          0
der7          0
der8          0
der9          0
der10         0
der11         0
der12         0
der13         0
der14         0
der15         0
der16         0
der17         0
der18         0
der19         0
cat1        307
cat2        145
cat3       8710
cat4        160
cat5          5
cat6     616911
cat7          0
cat8     400359
cat9          0
cat10     17331
cat11         0
cat12       877
cat13         0
cat14         0
dtype: int64

# filling null values of testing data with mean

testing data also contain null values so i also fill null values of test data with mean of their corresponding feature

In [318]:
for i in range(57):
    current_mean=test_data.iloc[:,i].mean()
    test_data.iloc[:,i].fillna(current_mean,inplace=True)

In [320]:
test_data.isnull().sum()

id       0
num1     0
num2     0
num3     0
num4     0
num5     0
num6     0
num7     0
num8     0
num9     0
num10    0
num11    0
num12    0
num13    0
num14    0
num15    0
num16    0
num17    0
num18    0
num19    0
num20    0
num21    0
num22    0
num23    0
der1     0
der2     0
der3     0
der4     0
der5     0
der6     0
der7     0
der8     0
der9     0
der10    0
der11    0
der12    0
der13    0
der14    0
der15    0
der16    0
der17    0
der18    0
der19    0
cat1     0
cat2     0
cat3     0
cat4     0
cat5     0
cat6     0
cat7     0
cat8     0
cat9     0
cat10    0
cat11    0
cat12    0
cat13    0
cat14    0
dtype: int64

# transforming test data according to training data using pca

In [321]:
X_test=pca.transform(test_data)

In [322]:
X_test.shape

(892816, 1)

In [325]:
X.shape

(595999, 1)

# applying decision tree on testing data and whole training data

In [324]:
dt.fit(X,Y)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [326]:
final_predictions=dt.predict(X_test)

In [342]:
final_predictions

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [343]:
final_predictions.shape

(892816,)

# saving predictions into system

In [347]:
np.savetxt("predictions.csv",final_predictions,delimiter=',',fmt='%f')